#pragma once
#include "../global/types.h"

void EFF_SetFogColor(ITEM_INFO* item);
void EFF_FinishLevel(ITEM_INFO* item);
void EFF_Turn180(ITEM_INFO* item);
void EFF_RumbleFX(ITEM_INFO* item);
void EFF_PlaySoundEffect(ITEM_INFO* item);
void EFF_RubbleFXLoop(ITEM_INFO* item);
void EFF_FloodSFX(ITEM_INFO* item);
void EFF_ActivateCamera(ITEM_INFO* item);
void EFF_ActivateKey(ITEM_INFO* item);
void EFF_SwapCrowbar(ITEM_INFO* item);
void EFF_PlayExplosionSoundEffect(ITEM_INFO* item);
void EFF_SetLaraLocation(ITEM_INFO* item);
void EFF_SetLaraLocationPad(ITEM_INFO* item);
void EFF_GhostTrap(ITEM_INFO* item);
void EFF_KillActiveCreatures(ITEM_INFO* item);
void KillActiveBaddies(bool doRemoveAndDisable);
void EFF_FreeLaraHands(ITEM_INFO* item);
void EFF_LaraDrawRightGun(ITEM_INFO* item);
void EFF_LaraDrawLeftGun(ITEM_INFO* item);
void EFF_LaraShootRightGun(ITEM_INFO* item);
void EFF_LaraShootLeftGun(ITEM_INFO* item);
void EFF_SwapMeshWithMeshswap1(ITEM_INFO* item);
void EFF_SwapMeshWithMeshswap2(ITEM_INFO* item);
void EFF_SwapMeshWithMeshswap3(ITEM_INFO* item);
void EFF_InvisibilityOn(ITEM_INFO* item);
void EFF_InvisibilityOff(ITEM_INFO* item);
void EFF_ResetHair(ITEM_INFO* item);
void EFF_ClearScarabBeetles(ITEM_INFO* item);
void EFF_MeshSwapToWaterSkin(ITEM_INFO* item);
void EFF_MeshSwapFromWaterSkin(ITEM_INFO* item);
void void_effect(ITEM_INFO* item);
void WaterFall(short item_number);
void WadeSplash(ITEM_INFO* item, long water, long depth);
void Splash(ITEM_INFO* item);
void EFF_FootSplash(ITEM_INFO* item, short extra);
short DoBloodSplat(long x, long y, long z, short speed, short ang, short room_number);
void DoLotsOfBlood(long x, long y, long z, short speed, short ang, short room_number, long num);
void Richochet(GAME_VECTOR* pos);
void SoundEffects();
long ItemNearLara(PHD_3DPOS* pos, long rad);

extern FX_INFO* effects;
extern OBJECT_VECTOR* sound_effects;
extern long GlobalFogOff;
extern long number_sound_effects;
extern DWORD FogTableColor[28];
extern void(*FlipEffectRoutines[])(ITEM_INFO* item);
extern void(*CreatureEffectRoutines[47])(ITEM_INFO* item, short extra);
